apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: llm-app
spec:
  target:
    service: gemma-4-31b-it-a100-disk
    port: 80
  # rules:
  #   - hosts:
  #       - sample-app.example.com
  scalingMetric:
    requestRate:
      targetValue: 1
      window: 1m
      granularity: 1s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-llm-http
spec:
  scaleTargetRef:
    name: gemma-4-31b-it-a100-disk
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 30
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: llm-app
